FROM node:20

# 作業ディレクトリを設定
WORKDIR /src

# package.jsonとpackage-lock.jsonをコピー
COPY package*.json ./

# 依存関係をインストール
RUN pnpm install

# ソースコードをコンテナにコピー
COPY . .

# 開発サーバー用のポートを公開
EXPOSE 5173

# Vite開発サーバーを起動
CMD ["pnpm", "run", "dev"]