version: "3.8"
services:
  backend:
    build:
      context: ./backend
    container_name: go-api
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend
      - /backend/tmp
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  db-data:
